config/routes.rb
Rails.application.routes.draw do

  root 'restaurants#index'

  get "/restaurants/new", to: "restaurants#new", as: :new_resto
  get "/restaurants", to: "restaurants#index", as: :restos
  get "restaurants/:id", to: "restaurants#show", as: :resto

  post "/restaurants/:id/reviews", to: "review#create"
  post "restaurants", to: "restaurants#create"

end

app/models/resto.rb
class Resto < ActiveRecord::Base
  has_many :reviews
end

app/models/review.rb
class Review < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Resto.all
  end

  def show
    @restaurant = Resto.find(params[:id])
  end

  def new #get
    @restaurant = Resto.new
  end

  def create #post
    Resto.create(restaurant_params)
    redirect_to restaurants_path
  end

  private
  def restaurant_params
    params.require(:resto).permit(:name, :adress, :phone, :category)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create #post
    @restaurant = Resto.find(params[:id])
    @review = (review_params)
    redirect_to restaurants_path
  end

  private
  def task_params
    params.require(:review).permit(:rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Restaurant</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/restaurants/index.html.erb
<p>Nos restaurants partenaires</p>

<%@restaurants.each do |restaurant| %>
<ul>
  <li>name : <%= restaurant.name%></li>
  <li>address : <%= restaurant.adress%></li>
  <li>phone : <%= restaurant.phone%></li>
  <li>category : <%= restaurant.category%></li>
  <li><%=link_to "show restaurant", resto_path(restaurant)%></li>
</ul>
<%end%>

<%= link_to "Add a restaurant", :action => "new" %>

app/views/restaurants/new.html.erb
<h1>Add a new restaurant</h1>

<%= form_for(@restaurant) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :adress %>
  <%= f.label :phone %>
  <%= f.text_field :phone %>
  <%= f.label :category %>
  <%= f.select :category, "chinese"=>"chinese", "italian"=>"italian" %>
  <%= f.submit %>
<% end %>

<%= link_to "Back restaurant's lits", :action => "index" %>

app/views/restaurants/show.html.erb
<p>name : <%=@restaurant.name%></p>
<p>phone : <%=@restaurant.phone%></p>
<p>adress : <%=@restaurant.adress%></p>
<p>category : <%=@restaurant.category%></p>

<h1>Add a note to this restaurant</h1>


<% @restaurant.reviews.each do |r|%>
<ul>
  <li>content : <%=r.content%> </li>
  <li>rating : <%=r.rating%> </li>
</ul>






<%= link_to "Back restaurant's lits", restos_path%>